FROM nvidia/cuda:13.2.0-devel-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3.11 python3.11-venv python3-pip git curl ninja-build build-essential
RUN ln -sf /usr/bin/python3.11 /usr/bin/python
RUN pip install uv
ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN which pip
RUN pip --version
RUN python -m site
